version: "3.9"
services: 
    data:
        image: smart_home_backend/data
        pull_policy: never
        restart: unless-stopped
        environment:
            - PSQL_USERNAME=vozer
            - PSQL_PASSWORD=wibuisthebest
            - PSQL_DB_NAME=smart_home
            - PSQL_HOSTNAME=postgres
            - AUTO_SERVICE_URL=http://auto:9010
        depends_on:
            - postgres
    connect:
        image: smart_home_backend/connect
        pull_policy: never
        restart: unless-stopped
        env_file:
            - ./adafruit.env
        environment:
            - DATA_SERVICE_URL=http://data:8000
        depends_on:
            - data
    auto:
        image: smart_home_backend/auto
        pull_policy: never
        restart: unless-stopped
        env_file:
            - ./adafruit.env
        environment:
            - DATA_SERVICE_URL=http://data:8000
        depends_on:
            - data
    postgres:
        image: postgres
        pull_policy: if_not_present
        restart: unless-stopped
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=psql
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./data/db:/docker-entrypoint-initdb.d/
    nginx:
        image: nginx
        pull_policy: if_not_present
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - data
            - connect
volumes: 
    pgdata: 
        external: true
